name: Test
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        required: true
        description: "プルリクエストの番号"
        default: ""

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        id: set-result
        uses: iwata-n/actions-pull-request-json@main
        with:
          pullRequestNumber: ${{github.event.inputs.pull_request_number}}
      - name: Get result steps
        run: echo ${{steps.set-result.outputs.result}}